concurrency:
  cancel-in-progress: true
  group: dep-checker-${{ github.head_ref || github.run_id }}-${{ github.base_ref }}
defaults:
  run:
    shell: bash
jobs:
  base-build:
    name: Check Dependencies
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout ${{ github.ref }} ( ${{ github.sha }} )
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        show-progress: false
        submodules: false
    - continue-on-error: true
      name: Check Dependencies
      run: 'mvn -q dependency:copy -Dartifact=org.apache.maven.indexer:search-backend-smo:7.1.1
        -DoutputDirectory=./lib

        mvn -q dependency:copy -Dartifact=org.apache.maven.indexer:search-api:7.1.1         -DoutputDirectory=./lib

        mvn -q dependency:copy -Dartifact=com.google.code.gson:gson:2.10.1                  -DoutputDirectory=./lib

        mvn -q dependency:copy -Dartifact=org.apache.maven:maven-artifact:3.9.6             -DoutputDirectory=./lib

        echo "<pre>" >> $GITHUB_STEP_SUMMARY

        $JAVA_HOME_21_X64/bin/java --enable-preview --source 21 -cp "lib/*" .github/scripts/BinariesListUpdates.java
        ./ | tee -a $GITHUB_STEP_SUMMARY

        echo "</pre>" >> $GITHUB_STEP_SUMMARY

        rm -Rf lib

        '
    timeout-minutes: 20
name: NetBeans Dependency Checks
on:
  repository_dispatch:
    types: trigger-ga___dependency-checks.yml
