concurrency:
  cancel-in-progress: true
  group: dlight-${{ github.head_ref || github.run_id }}-${{ github.base_ref }}
jobs:
  build-linux:
    name: Build on Linux
    needs: source
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download sources
      uses: actions/download-artifact@v4
      with:
        name: nativeexecution-external-sources
    - continue-on-error: true
      name: Build native lib (64-bit)
      run: 'echo "Building 64-bit binary"

        rm -rf ../release/bin/nativeexecution/Linux-x86_64/*

        rm -rf buildall/*

        chmod +x buildjob.sh

        ./buildjob.sh Linux x86_64

        ls -l -R buildall/

        echo "done"

        '
      working-directory: ide/dlight.nativeexecution/tools
    - continue-on-error: true
      name: Upload artifact Linux 64 bit
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: Linux-x86_64
        path: ide/dlight.nativeexecution/tools/buildall/
  build-macos-arm:
    name: Build on MacOS arm64
    needs: source
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download sources
      uses: actions/download-artifact@v4
      with:
        name: nativeexecution-external-sources
    - continue-on-error: true
      name: Build native lib (arm64)
      run: 'rm -rf ../release/bin/nativeexecution/Linux-MacOSX*/*

        rm -rf buildall/*

        chmod +x buildjob.sh

        ./buildjob.sh MacOSX arm

        ls -l -R buildall/

        '
      working-directory: ide/dlight.nativeexecution/tools
    - continue-on-error: true
      name: Upload artifact macOS arm64
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: MacOSX-arm_64
        path: ide/dlight.nativeexecution/tools/buildall/
  build-macos-x64:
    name: Build on MacOS x86_64
    needs: source
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download sources
      uses: actions/download-artifact@v4
      with:
        name: nativeexecution-external-sources
    - continue-on-error: true
      name: Build native lib (x86_64)
      run: 'rm -rf ../release/bin/nativeexecution/Linux-MacOSX*/*

        rm -rf buildall/*

        chmod +x buildjob.sh

        ./buildjob.sh MacOSX x86_64

        ls -l -R buildall/

        '
      working-directory: ide/dlight.nativeexecution/tools
    - continue-on-error: true
      name: Upload artifact macOS x86_64
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: MacOSX-x86_64
        path: ide/dlight.nativeexecution/tools/buildall/
  build-zip-with-build-artifacts:
    name: Package Native Execution Libraries
    needs:
    - build-linux
    - build-macos-x64
    - build-macos-arm
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Create dir structure
      run: mkdir -p myfiles/
    - continue-on-error: true
      name: Download artifacts from predecessor jobs
      uses: actions/download-artifact@v4
      with:
        path: myfiles/
    - continue-on-error: true
      name: Tidy up and display artifacts
      run: 'cp myfiles/nativeexecution-external-sources/LICENSE myfiles/LICENSE

        cp myfiles/nativeexecution-external-sources/NOTICE myfiles/NOTICE

        rm -rf myfiles/*sources*

        ls -l -R

        '
    - continue-on-error: true
      name: Create BUILDINFO
      run: 'BUILDINFO="myfiles/BUILDINFO.txt"

        touch "$BUILDINFO"

        echo "Apache NetBeans"                                                >> "$BUILDINFO"

        echo ""                                                               >> "$BUILDINFO"

        echo "Binaries in this ZIP are..."                                    >> "$BUILDINFO"

        echo "Build by GitHub Actions Workflow: ${GITHUB_WORKFLOW}"           >> "$BUILDINFO"

        echo ""                                                               >> "$BUILDINFO"

        echo "Build from:"                                                    >> "$BUILDINFO"

        echo "   Git repo       : ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"  >> "$BUILDINFO"

        echo "   Git commit SHA : ${GITHUB_SHA}"                              >> "$BUILDINFO"

        echo "   Git ref        : ${GITHUB_REF}"                              >> "$BUILDINFO"

        echo ""                                                               >> "$BUILDINFO"

        echo "Build time UTC : $(date --rfc-3339=seconds --utc)"              >> "$BUILDINFO"

        echo ""                                                               >> "$BUILDINFO"

        '
    - continue-on-error: true
      name: Upload bundle
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: nativeexecution-external-binaries
        path: myfiles/
  source:
    name: Build Source Zip
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        show-progress: false
        submodules: false
    - continue-on-error: true
      name: Generate source bundle
      run: 'SOURCES="ide/dlight.nativeexecution/build/sources"

        mkdir -p ${SOURCES}/ide/dlight.nativeexecution

        cp -r ide/dlight.nativeexecution/tools/ ${SOURCES}/ide/dlight.nativeexecution/

        cp -r ide/dlight.nativeexecution/release/ ${SOURCES}/ide/dlight.nativeexecution/

        cp LICENSE ${SOURCES}/LICENSE

        cp NOTICE ${SOURCES}/NOTICE

        ls -l -R ${SOURCES}

        '
    - continue-on-error: true
      name: Upload native sources
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: nativeexecution-external-sources
        path: ide/dlight.nativeexecution/build/sources/
name: NetBeans Native Execution Libraries
on:
  repository_dispatch:
    types: trigger-ga___native-binary-build-dlight.nativeexecution.yml
