concurrency:
  cancel-in-progress: true
  group: launcher-${{ github.head_ref || github.run_id }}-${{ github.base_ref }}
jobs:
  build-linux:
    name: Build with MinGW
    needs: source
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Install MinGW
      run: sudo apt install mingw-w64 mingw-w64-tools
    - continue-on-error: true
      name: Download sources
      uses: actions/download-artifact@v4
      with:
        name: launcher-external-sources
    - continue-on-error: true
      name: Build bootstrap binaries
      run: 'echo "Building bootstrap binaries"

        rm -rf ./build/

        make -f Makefile.mingw

        ls -l -R ./build/

        echo "done"

        '
      working-directory: platform/o.n.bootstrap/launcher/windows/
    - continue-on-error: true
      name: Upload bootstrap artifacts
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: launcher-bootstrap-bin
        path: platform/o.n.bootstrap/launcher/windows/build/
    - continue-on-error: true
      name: Build harness binaries
      run: 'echo "Building harness binaries"

        rm -rf ./build/

        make -f Makefile.mingw

        ls -l -R ./build/

        echo "done"

        '
      working-directory: harness/apisupport.harness/windows-launcher-src
    - continue-on-error: true
      name: Upload harness artifacts
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: launcher-harness-bin
        path: harness/apisupport.harness/windows-launcher-src/build/
    - continue-on-error: true
      name: Build IDE binaries
      run: 'echo "Building IDE binaries"

        rm -rf ./build/

        make -f Makefile.mingw

        ls -l -R ./build/

        echo "done"

        '
      working-directory: nb/ide.launcher/windows
    - continue-on-error: true
      name: Upload IDE artifacts
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: launcher-ide-bin
        path: nb/ide.launcher/windows/build/
  build-zip-with-build-artifacts:
    name: Package Binaries
    needs:
    - build-linux
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Create dir structure
      run: mkdir -p myfiles/
    - continue-on-error: true
      name: Download artifacts from predecessor jobs
      uses: actions/download-artifact@v4
      with:
        path: myfiles/
    - continue-on-error: true
      name: Tidy up and display artifacts
      run: 'cp myfiles/launcher-external-sources/LICENSE myfiles/LICENSE

        cp myfiles/launcher-external-sources/NOTICE myfiles/NOTICE

        cp myfiles/*bin/*.exe myfiles/

        cp myfiles/*bin/*.dll myfiles/

        rm -rf myfiles/*-sources/

        rm -rf myfiles/*-bin/

        ls -l -R

        '
    - continue-on-error: true
      name: Create BUILDINFO
      run: 'BUILDINFO="myfiles/BUILDINFO.txt"

        touch "$BUILDINFO"

        echo "Apache NetBeans"                                                >> "$BUILDINFO"

        echo ""                                                               >> "$BUILDINFO"

        echo "Binaries in this ZIP are..."                                    >> "$BUILDINFO"

        echo "Build by GitHub Actions Workflow: ${GITHUB_WORKFLOW}"           >> "$BUILDINFO"

        echo ""                                                               >> "$BUILDINFO"

        echo "Build from:"                                                    >> "$BUILDINFO"

        echo "   Git repo       : ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"  >> "$BUILDINFO"

        echo "   Git commit SHA : ${GITHUB_SHA}"                              >> "$BUILDINFO"

        echo "   Git ref        : ${GITHUB_REF}"                              >> "$BUILDINFO"

        echo ""                                                               >> "$BUILDINFO"

        echo "Build time UTC : $(date --rfc-3339=seconds --utc)"              >> "$BUILDINFO"

        echo ""                                                               >> "$BUILDINFO"

        '
    - continue-on-error: true
      name: Upload bundle
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: launcher-external-binaries
        path: myfiles/
  source:
    name: Package Sources
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        show-progress: false
        submodules: false
    - continue-on-error: true
      name: Generate source bundle
      run: 'SOURCES="nbbuild/build/native/launcher/sources"

        mkdir -p ${SOURCES}/platform/o.n.bootstrap/launcher/

        cp -r platform/o.n.bootstrap/launcher/windows/ ${SOURCES}/platform/o.n.bootstrap/launcher/

        mkdir -p ${SOURCES}/harness/apisupport.harness/

        cp -r harness/apisupport.harness/windows-launcher-src/ ${SOURCES}/harness/apisupport.harness/

        mkdir -p ${SOURCES}/nb/ide.launcher/

        cp -r nb/ide.launcher/windows/ ${SOURCES}/nb/ide.launcher/

        cp LICENSE ${SOURCES}/LICENSE

        cp NOTICE ${SOURCES}/NOTICE

        ls -l -R ${SOURCES}

        '
    - continue-on-error: true
      name: Upload native sources
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: launcher-external-sources
        path: nbbuild/build/native/launcher/sources/
name: NetBeans Native Launcher
on:
  repository_dispatch:
    types: trigger-ga___native-binary-build-launcher.yml
